
textColor = (
    ("" , "NONE"),

    ("w3-text-red" , "Red"),
    ("w3-text-pink" , "Pink"),
    ("w3-text-purple" , "Purple"),
    ("w3-text-deep-purple" , "Deep Purple"),
    ("w3-text-indigo" , "Indigo"),
    ("w3-text-blue" , "Blue"),
    ("w3-text-light-blue" , "Light Blue"),
    ("w3-text-cyan" , "Cyan"),
    ("w3-text-aqua" , "Aqua"),
    ("w3-text-teal" , "Teal"),
    ("w3-text-green" , "Green"),
    ("w3-text-light-green" , "Light Green"),
    ("w3-text-lime" , "Lime"),
    ("w3-text-sand" , "Sand"),
    ("w3-text-khaki" , "Khaki"),
    ("w3-text-yellow" , "Yellow"),
    ("w3-text-amber" , "Amber"),
    ("w3-text-orange" , "Orange"),
    ("w3-text-deep-orange" , "Deep Orange"),
    ("w3-text-blue-grey" , "Blue Grey"),
    ("w3-text-brown" , "Brown"),
    ("w3-text-light-grey" , "Light Grey"),
    ("w3-text-grey" , "Grey"),
    ("w3-text-dark-grey" , "Dark Grey"),
    ("w3-text-pale-red" , "Pale Red"),
    ("w3-text-pale-yellow" , "Pale Yellow"),
    ("w3-text-pale-green" , "Pale Green"),
    ("w3-text-pale-blue" , "Pale Blue"),
     )

bgColor = (
    ("" , "NONE"),

    ("w3-red" , "Red"),
    ("w3-pink" , "Pink"),
    ("w3-purple" , "Purple"),
    ("w3-deep-purple" , "Deep Purple"),
    ("w3-indigo" , "Indigo"),
    ("w3-blue" , "Blue"),
    ("w3-light-blue" , "Light Blue"),
    ("w3-cyan" , "Cyan"),
    ("w3-aqua" , "Aqua"),
    ("w3-teal" , "Teal"),
    ("w3-green" , "Green"),
    ("w3-light-green" , "Light Green"),
    ("w3-lime" , "Lime"),
    ("w3-sand" , "Sand"),
    ("w3-khaki" , "Khaki"),
    ("w3-yellow" , "Yellow"),
    ("w3-amber" , "Amber"),
    ("w3-orange" , "Orange"),
    ("w3-deep-orange" , "Deep Orange"),
    ("w3-blue-grey" , "Blue Grey"),
    ("w3-brown" , "Brown"),
    ("w3-light-grey" , "Light Grey"),
    ("w3-grey" , "Grey"),
    ("w3-dark-grey" , "Dark Grey"),
    ("w3-pale-red" , "Pale Red"),
    ("w3-pale-yellow" , "Pale Yellow"),
    ("w3-pale-green" , "Pale Green"),
    ("w3-pale-blue" , "Pale Blue"),
     )

textSize = (
	("w3-tiny", "tiny"),
    ("w3-small", "small"),
    ("w3-medium", "medium"),
    ("w3-large", "large"),
    ("w3-xlarge", "xlarge"),
    ("w3-xxlarge", "xxlarge"),
    ("w3-xxxlarge", "xxxlarge"),
    ("w3-jumbo", "jumbo"),
    )


textFont = (
    ('Aclonica', 'Aclonica'),
    ('Allan', 'Allan'),
    ('Allerta', 'Allerta'),
    ('Allerta Stencil', 'Allerta Stencil'),
    ('Amaranth', 'Amaranth'),
    ('Angkor', 'Angkor'),
    ('Annie Use Your Telescope', 'Annie Use Your Telescope'),
    ('Anonymous Pro', 'Anonymous Pro'),
    ('Anton', 'Anton'),
    ('Architects Daughter', 'Architects Daughter'),
    ('Arimo', 'Arimo'),
    ('Artifika', 'Artifika'),
    ('Arvo', 'Arvo'),
    ('Astloch', 'Astloch'),
    ('Bangers', 'Bangers'),
    ('Battambang', 'Battambang'),
    ('Bayon', 'Bayon'),
    ('Bentham', 'Bentham'),
    ('Bevan', 'Bevan'),
    ('Bigshot One', 'Bigshot One'),
    ('Bokor', 'Bokor'),
    ('Brawler', 'Brawler'),
    ('Buda', 'Buda'),
    ('Cabin', 'Cabin'),
    ('Cabin Sketch', 'Cabin Sketch'),
    ('Calligraffitti', 'Calligraffitti'),
    ('Candal', 'Candal'),
    ('Cantarell', 'Cantarell'),
    ('Cardo', 'Cardo'),
    ('Carter One', 'Carter One'),
    ('Caudex', 'Caudex'),
    ('Chenla', 'Chenla'),
    ('Cherry Cream Soda', 'Cherry Cream Soda'),
    ('Chewy', 'Chewy'),
    ('Coda', 'Coda'),
    ('Coda Caption', 'Coda Caption'),
    ('Coming Soon', 'Coming Soon'),
    ('Content', 'Content'),
    ('Copse', 'Copse'),
    ('Corben', 'Corben'),
    ('Cousine', 'Cousine'),
    ('Covered By Your Grace', 'Covered By Your Grace'),
    ('Crafty Girls', 'Crafty Girls'),
    ('Crimson Text', 'Crimson Text'),
    ('Crushed', 'Crushed'),
    ('Cuprum', 'Cuprum'),
    ('Damion', 'Damion'),
    ('Dancing Script', 'Dancing Script'),
    ('Dangrek', 'Dangrek'),
    ('Dawning of a New Day', 'Dawning of a New Day'),
    ('Didact Gothic', 'Didact Gothic'),
    ('Droid Sans', 'Droid Sans'),
    ('Droid Sans Mono', 'Droid Sans Mono'),
    ('Droid Serif', 'Droid Serif'),
    ('EB Garamond', 'EB Garamond'),
    ('Expletus Sans', 'Expletus Sans'),
    ('Fontdiner Swanky', 'Fontdiner Swanky'),
    ('Francois One', 'Francois One'),
    ('Freehand', 'Freehand'),
    ('GFS Didot', 'GFS Didot'),
    ('GFS Neohellenic', 'GFS Neohellenic'),
    ('Geo', 'Geo'),
    ('Goudy Bookletter 1911', 'Goudy Bookletter 1911'),
    ('Gruppo', 'Gruppo'),
    ('Handlee', 'Handlee'),
    ('Hanuman', 'Hanuman'),
    ('Holtwood One SC', 'Holtwood One SC'),
    ('Homemade Apple', 'Homemade Apple'),
    ('IM Fell DW Pica', 'IM Fell DW Pica'),
    ('IM Fell DW Pica SC', 'IM Fell DW Pica SC'),
    ('IM Fell Double Pica', 'IM Fell Double Pica'),
    ('IM Fell Double Pica SC', 'IM Fell Double Pica SC'),
    ('IM Fell English', 'IM Fell English'),
    ('IM Fell English SC', 'IM Fell English SC'),
    ('IM Fell French Canon', 'IM Fell French Canon'),
    ('IM Fell French Canon SC', 'IM Fell French Canon SC'),
    ('IM Fell Great Primer', 'IM Fell Great Primer'),
    ('IM Fell Great Primer SC', 'IM Fell Great Primer SC'),
    ('Inconsolata', 'Inconsolata'),
    ('Indie Flower', 'Indie Flower'),
    ('Irish Grover', 'Irish Grover'),
    ('Josefin Sans', 'Josefin Sans'),
    ('Josefin Slab', 'Josefin Slab'),
    ('Judson', 'Judson'),
    ('Jura', 'Jura'),
    ('Just Another Hand', 'Just Another Hand'),
    ('Just Me Again Down Here', 'Just Me Again Down Here'),
    ('Kenia', 'Kenia'),
    ('Khmer', 'Khmer'),
    ('Koulen', 'Koulen'),
    ('Kranky', 'Kranky'),
    ('Kreon', 'Kreon'),
    ('Kristi', 'Kristi'),
    ('Lato', 'Lato'),
    ('League Script', 'League Script'),
    ('Lekton', 'Lekton'),
    ('Limelight', 'Limelight'),
    ('Lobster', 'Lobster'),
    ('Lora', 'Lora'),
    ('Luckiest Guy', 'Luckiest Guy'),
    ('Maiden Orange', 'Maiden Orange'),
    ('Mako', 'Mako'),
    ('Maven Pro', 'Maven Pro'),
    ('Meddon', 'Meddon'),
    ('MedievalSharp', 'MedievalSharp'),
    ('Megrim', 'Megrim'),
    ('Merriweather', 'Merriweather'),
    ('Metal', 'Metal'),
    ('Metrophobic', 'Metrophobic'),
    ('Michroma', 'Michroma'),
    ('Miltonian', 'Miltonian'),
    ('Miltonian Tattoo', 'Miltonian Tattoo'),
    ('Molengo', 'Molengo'),
    ('Monofett', 'Monofett'),
    ('Moul', 'Moul'),
    ('Moulpali', 'Moulpali'),
    ('Mountains of Christmas', 'Mountains of Christmas'),
    ('Muli', 'Muli'),
    ('Neucha', 'Neucha'),
    ('Neuton', 'Neuton'),
    ('News Cycle', 'News Cycle'),
    ('Nobile', 'Nobile'),
    ('Nova Cut', 'Nova Cut'),
    ('Nova Flat', 'Nova Flat'),
    ('Nova Mono', 'Nova Mono'),
    ('Nova Oval', 'Nova Oval'),
    ('Nova Round', 'Nova Round'),
    ('Nova Script', 'Nova Script'),
    ('Nova Slim', 'Nova Slim'),
    ('Nova Square', 'Nova Square'),
    ('Nunito', 'Nunito'),
    ('OFL Sorts Mill Goudy TT', 'OFL Sorts Mill Goudy TT'),
    ('Odor Mean Chey', 'Odor Mean Chey'),
    ('Old Standard TT', 'Old Standard TT'),
    ('Open Sans', 'Open Sans'),
    ('Open Sans Condensed', 'Open Sans Condensed'),
    ('Orbitron', 'Orbitron'),
    ('Oswald', 'Oswald'),
    ('Over the Rainbow', 'Over the Rainbow'),
    ('PT Sans', 'PT Sans'),
    ('PT Sans Caption', 'PT Sans Caption'),
    ('PT Sans Narrow', 'PT Sans Narrow'),
    ('PT Serif', 'PT Serif'),
    ('PT Serif Caption', 'PT Serif Caption'),
    ('Pacifico', 'Pacifico'),
    ('Paytone One', 'Paytone One'),
    ('Permanent Marker', 'Permanent Marker'),
    ('Philosopher', 'Philosopher'),
    ('Play', 'Play'),
    ('Playfair Display', 'Playfair Display'),
    ('Podkova', 'Podkova'),
    ('Preahvihear', 'Preahvihear'),
    ('Puritan', 'Puritan'),
    ('Quattrocento', 'Quattrocento'),
    ('Quattrocento Sans', 'Quattrocento Sans'),
    ('Radley', 'Radley'),
    ('Raleway', 'Raleway'),
    ('Reenie Beanie', 'Reenie Beanie'),
    ('Rock Salt', 'Rock Salt'),
    ('Rokkitt', 'Rokkitt'),
    ('Ruslan Display', 'Ruslan Display'),
    ('Schoolbell', 'Schoolbell'),
    ('Shanti', 'Shanti'),
    ('Siemreap', 'Siemreap'),
    ('Sigmar One', 'Sigmar One'),
    ('Six Caps', 'Six Caps'),
    ('Slackey', 'Slackey'),
    ('Smythe', 'Smythe'),
    ('Sniglet', 'Sniglet'),
    ('Special Elite', 'Special Elite'),
    ('Sue Ellen Francisco', 'Sue Ellen Francisco'),
    ('Sunshiney', 'Sunshiney'),
    ('Suwannaphum', 'Suwannaphum'),
    ('Swanky and Moo Moo', 'Swanky and Moo Moo'),
    ('Syncopate', 'Syncopate'),
    ('Tangerine', 'Tangerine'),
    ('Taprom', 'Taprom'),
    ('Tenor Sans', 'Tenor Sans'),
    ('Terminal Dosis Light', 'Terminal Dosis Light'),
    ('The Girl Next Door', 'The Girl Next Door'),
    ('Tinos', 'Tinos'),
    ('Ubuntu', 'Ubuntu'),
    ('Ultra', 'Ultra'),
    ('UnifrakturCook', 'UnifrakturCook'),
    ('UnifrakturMaguntia', 'UnifrakturMaguntia'),
    ('Unkempt', 'Unkempt'),
    ('VT323', 'VT323'),
    ('Vibur', 'Vibur'),
    ('Vollkorn', 'Vollkorn'),
    ('Waiting for the Sunrise', 'Waiting for the Sunrise'),
    ('Wallpoet', 'Wallpoet'),
    ('Walter Turncoat', 'Walter Turncoat'),
    ('Wire One', 'Wire One'),
    ('Yanone Kaffeesatz','Yanone Kaffeesatz'),
    )
